package model;
// Generated 29 mars 2016 13:18:27 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AgentMedical generated by hbm2java
 */
public class AgentMedical  implements java.io.Serializable {


     private Integer idagent;
     private CentreMedical centreMedical;
     private Integer passwordagent;
     private String nomagent;
     private String prenomagent;
     private String emailagent;
     private String nomvilleagent;
     private String nompadresseagent;
     private Integer codepostalagent;
     private Integer telagent;
     private Integer typeagent;
     private Integer lon;
     private Integer lat;
     private Set<CentreMedical> centreMedicals = new HashSet<CentreMedical>(0);
     private Set<Commentaire> commentaires = new HashSet<Commentaire>(0);
     private Set<Article> articles = new HashSet<Article>(0);
     private Set<Profil> profils = new HashSet<Profil>(0);

    public AgentMedical() {
    }

    public AgentMedical(CentreMedical centreMedical, Integer passwordagent, String nomagent, String prenomagent, String emailagent, String nomvilleagent, String nompadresseagent, Integer codepostalagent, Integer telagent, Integer typeagent, Integer lon, Integer lat, Set<CentreMedical> centreMedicals, Set<Commentaire> commentaires, Set<Article> articles, Set<Profil> profils) {
       this.centreMedical = centreMedical;
       this.passwordagent = passwordagent;
       this.nomagent = nomagent;
       this.prenomagent = prenomagent;
       this.emailagent = emailagent;
       this.nomvilleagent = nomvilleagent;
       this.nompadresseagent = nompadresseagent;
       this.codepostalagent = codepostalagent;
       this.telagent = telagent;
       this.typeagent = typeagent;
       this.lon = lon;
       this.lat = lat;
       this.centreMedicals = centreMedicals;
       this.commentaires = commentaires;
       this.articles = articles;
       this.profils = profils;
    }
   
    public Integer getIdagent() {
        return this.idagent;
    }
    
    public void setIdagent(Integer idagent) {
        this.idagent = idagent;
    }
    public CentreMedical getCentreMedical() {
        return this.centreMedical;
    }
    
    public void setCentreMedical(CentreMedical centreMedical) {
        this.centreMedical = centreMedical;
    }
    public Integer getPasswordagent() {
        return this.passwordagent;
    }
    
    public void setPasswordagent(Integer passwordagent) {
        this.passwordagent = passwordagent;
    }
    public String getNomagent() {
        return this.nomagent;
    }
    
    public void setNomagent(String nomagent) {
        this.nomagent = nomagent;
    }
    public String getPrenomagent() {
        return this.prenomagent;
    }
    
    public void setPrenomagent(String prenomagent) {
        this.prenomagent = prenomagent;
    }
    public String getEmailagent() {
        return this.emailagent;
    }
    
    public void setEmailagent(String emailagent) {
        this.emailagent = emailagent;
    }
    public String getNomvilleagent() {
        return this.nomvilleagent;
    }
    
    public void setNomvilleagent(String nomvilleagent) {
        this.nomvilleagent = nomvilleagent;
    }
    public String getNompadresseagent() {
        return this.nompadresseagent;
    }
    
    public void setNompadresseagent(String nompadresseagent) {
        this.nompadresseagent = nompadresseagent;
    }
    public Integer getCodepostalagent() {
        return this.codepostalagent;
    }
    
    public void setCodepostalagent(Integer codepostalagent) {
        this.codepostalagent = codepostalagent;
    }
    public Integer getTelagent() {
        return this.telagent;
    }
    
    public void setTelagent(Integer telagent) {
        this.telagent = telagent;
    }
    public Integer getTypeagent() {
        return this.typeagent;
    }
    
    public void setTypeagent(Integer typeagent) {
        this.typeagent = typeagent;
    }
    public Integer getLon() {
        return this.lon;
    }
    
    public void setLon(Integer lon) {
        this.lon = lon;
    }
    public Integer getLat() {
        return this.lat;
    }
    
    public void setLat(Integer lat) {
        this.lat = lat;
    }
    public Set<CentreMedical> getCentreMedicals() {
        return this.centreMedicals;
    }
    
    public void setCentreMedicals(Set<CentreMedical> centreMedicals) {
        this.centreMedicals = centreMedicals;
    }
    public Set<Commentaire> getCommentaires() {
        return this.commentaires;
    }
    
    public void setCommentaires(Set<Commentaire> commentaires) {
        this.commentaires = commentaires;
    }
    public Set<Article> getArticles() {
        return this.articles;
    }
    
    public void setArticles(Set<Article> articles) {
        this.articles = articles;
    }
    public Set<Profil> getProfils() {
        return this.profils;
    }
    
    public void setProfils(Set<Profil> profils) {
        this.profils = profils;
    }




}


