package model;
// Generated 27 mars 2016 14:38:31 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AgentMedical generated by hbm2java
 */
public class AgentMedical  implements java.io.Serializable {


     private Integer idagent;
     private CentreMedical centreMedical;
     private String nomagent;
     private String prenomagent;
     private String pseudoagent;
     private String emailagent;
     private String passwordagent;
     private String nomvilleagent;
     private String nometatagent;
     private String nompaysagent;
     private Integer codepostalagent;
     private Integer typeagent;
     private Set<CentreMedical> centreMedicals = new HashSet<CentreMedical>(0);
     private Set<Commentaire> commentaires = new HashSet<Commentaire>(0);
     private Set<Article> articles = new HashSet<Article>(0);
     private Set<Profil> profils = new HashSet<Profil>(0);

    public AgentMedical() {
    }

    public AgentMedical(CentreMedical centreMedical, String nomagent, String prenomagent, String pseudoagent, String emailagent, String passwordagent, String nomvilleagent, String nometatagent, String nompaysagent, Integer codepostalagent, Integer typeagent, Set<CentreMedical> centreMedicals, Set<Commentaire> commentaires, Set<Article> articles, Set<Profil> profils) {
       this.centreMedical = centreMedical;
       this.nomagent = nomagent;
       this.prenomagent = prenomagent;
       this.pseudoagent = pseudoagent;
       this.emailagent = emailagent;
       this.passwordagent = passwordagent;
       this.nomvilleagent = nomvilleagent;
       this.nometatagent = nometatagent;
       this.nompaysagent = nompaysagent;
       this.codepostalagent = codepostalagent;
       this.typeagent = typeagent;
       this.centreMedicals = centreMedicals;
       this.commentaires = commentaires;
       this.articles = articles;
       this.profils = profils;
    }
   
    public Integer getIdagent() {
        return this.idagent;
    }
    
    public void setIdagent(Integer idagent) {
        this.idagent = idagent;
    }
    public CentreMedical getCentreMedical() {
        return this.centreMedical;
    }
    
    public void setCentreMedical(CentreMedical centreMedical) {
        this.centreMedical = centreMedical;
    }
    public String getNomagent() {
        return this.nomagent;
    }
    
    public void setNomagent(String nomagent) {
        this.nomagent = nomagent;
    }
    public String getPrenomagent() {
        return this.prenomagent;
    }
    
    public void setPrenomagent(String prenomagent) {
        this.prenomagent = prenomagent;
    }
    public String getPseudoagent() {
        return this.pseudoagent;
    }
    
    public void setPseudoagent(String pseudoagent) {
        this.pseudoagent = pseudoagent;
    }
    public String getEmailagent() {
        return this.emailagent;
    }
    
    public void setEmailagent(String emailagent) {
        this.emailagent = emailagent;
    }
    public String getPasswordagent() {
        return this.passwordagent;
    }
    
    public void setPasswordagent(String passwordagent) {
        this.passwordagent = passwordagent;
    }
    public String getNomvilleagent() {
        return this.nomvilleagent;
    }
    
    public void setNomvilleagent(String nomvilleagent) {
        this.nomvilleagent = nomvilleagent;
    }
    public String getNometatagent() {
        return this.nometatagent;
    }
    
    public void setNometatagent(String nometatagent) {
        this.nometatagent = nometatagent;
    }
    public String getNompaysagent() {
        return this.nompaysagent;
    }
    
    public void setNompaysagent(String nompaysagent) {
        this.nompaysagent = nompaysagent;
    }
    public Integer getCodepostalagent() {
        return this.codepostalagent;
    }
    
    public void setCodepostalagent(Integer codepostalagent) {
        this.codepostalagent = codepostalagent;
    }
    public Integer getTypeagent() {
        return this.typeagent;
    }
    
    public void setTypeagent(Integer typeagent) {
        this.typeagent = typeagent;
    }
    public Set<CentreMedical> getCentreMedicals() {
        return this.centreMedicals;
    }
    
    public void setCentreMedicals(Set<CentreMedical> centreMedicals) {
        this.centreMedicals = centreMedicals;
    }
    public Set<Commentaire> getCommentaires() {
        return this.commentaires;
    }
    
    public void setCommentaires(Set<Commentaire> commentaires) {
        this.commentaires = commentaires;
    }
    public Set<Article> getArticles() {
        return this.articles;
    }
    
    public void setArticles(Set<Article> articles) {
        this.articles = articles;
    }
    public Set<Profil> getProfils() {
        return this.profils;
    }
    
    public void setProfils(Set<Profil> profils) {
        this.profils = profils;
    }




}


