package model;
// Generated 30 mars 2016 10:59:16 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Article generated by hbm2java
 */
@Entity
@Table(name="article"
    ,catalog="pcd"
)
public class Article  implements java.io.Serializable {


     private Integer idarticle;
     private AgentMedical agentMedical;
     private Forum forum;
     private String articlecontent;
     private Set<Commentaire> commentaires = new HashSet<Commentaire>(0);

    public Article() {
    }

    public Article(AgentMedical agentMedical, Forum forum, String articlecontent, Set<Commentaire> commentaires) {
       this.agentMedical = agentMedical;
       this.forum = forum;
       this.articlecontent = articlecontent;
       this.commentaires = commentaires;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idarticle", unique=true, nullable=false)
    public Integer getIdarticle() {
        return this.idarticle;
    }
    
    public void setIdarticle(Integer idarticle) {
        this.idarticle = idarticle;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idagent")
    public AgentMedical getAgentMedical() {
        return this.agentMedical;
    }
    
    public void setAgentMedical(AgentMedical agentMedical) {
        this.agentMedical = agentMedical;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idforum")
    public Forum getForum() {
        return this.forum;
    }
    
    public void setForum(Forum forum) {
        this.forum = forum;
    }

    
    @Column(name="articlecontent")
    public String getArticlecontent() {
        return this.articlecontent;
    }
    
    public void setArticlecontent(String articlecontent) {
        this.articlecontent = articlecontent;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="article")
    public Set<Commentaire> getCommentaires() {
        return this.commentaires;
    }
    
    public void setCommentaires(Set<Commentaire> commentaires) {
        this.commentaires = commentaires;
    }




}


