package model;
// Generated 27 mars 2016 14:38:31 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Article generated by hbm2java
 */
public class Article  implements java.io.Serializable {


     private Integer idarticle;
     private AgentMedical agentMedical;
     private Forum forum;
     private String articlecontent;
     private Set<Commentaire> commentaires = new HashSet<Commentaire>(0);

    public Article() {
    }

    public Article(AgentMedical agentMedical, Forum forum, String articlecontent, Set<Commentaire> commentaires) {
       this.agentMedical = agentMedical;
       this.forum = forum;
       this.articlecontent = articlecontent;
       this.commentaires = commentaires;
    }
   
    public Integer getIdarticle() {
        return this.idarticle;
    }
    
    public void setIdarticle(Integer idarticle) {
        this.idarticle = idarticle;
    }
    public AgentMedical getAgentMedical() {
        return this.agentMedical;
    }
    
    public void setAgentMedical(AgentMedical agentMedical) {
        this.agentMedical = agentMedical;
    }
    public Forum getForum() {
        return this.forum;
    }
    
    public void setForum(Forum forum) {
        this.forum = forum;
    }
    public String getArticlecontent() {
        return this.articlecontent;
    }
    
    public void setArticlecontent(String articlecontent) {
        this.articlecontent = articlecontent;
    }
    public Set<Commentaire> getCommentaires() {
        return this.commentaires;
    }
    
    public void setCommentaires(Set<Commentaire> commentaires) {
        this.commentaires = commentaires;
    }




}


