package model;
// Generated 26 mars 2016 16:46:25 by Hibernate Tools 4.3.1



/**
 * Commentaire generated by hbm2java
 */
public class Commentaire  implements java.io.Serializable {


     private int idcommentaire;
     private AgentMedical agentMedical;
     private Article article;
     private Membre membre;
     private Note note;
     private String commentairecontent;

    public Commentaire() {
    }

	
    public Commentaire(int idcommentaire) {
        this.idcommentaire = idcommentaire;
    }
    public Commentaire(int idcommentaire, AgentMedical agentMedical, Article article, Membre membre, Note note, String commentairecontent) {
       this.idcommentaire = idcommentaire;
       this.agentMedical = agentMedical;
       this.article = article;
       this.membre = membre;
       this.note = note;
       this.commentairecontent = commentairecontent;
    }
   
    public int getIdcommentaire() {
        return this.idcommentaire;
    }
    
    public void setIdcommentaire(int idcommentaire) {
        this.idcommentaire = idcommentaire;
    }
    public AgentMedical getAgentMedical() {
        return this.agentMedical;
    }
    
    public void setAgentMedical(AgentMedical agentMedical) {
        this.agentMedical = agentMedical;
    }
    public Article getArticle() {
        return this.article;
    }
    
    public void setArticle(Article article) {
        this.article = article;
    }
    public Membre getMembre() {
        return this.membre;
    }
    
    public void setMembre(Membre membre) {
        this.membre = membre;
    }
    public Note getNote() {
        return this.note;
    }
    
    public void setNote(Note note) {
        this.note = note;
    }
    public String getCommentairecontent() {
        return this.commentairecontent;
    }
    
    public void setCommentairecontent(String commentairecontent) {
        this.commentairecontent = commentairecontent;
    }




}


