package model;
// Generated 24 avr. 2016 23:55:02 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Commentaire generated by hbm2java
 */
public class Commentaire  implements java.io.Serializable {


     private Integer idcommentaire;
     private AgentMedical agentMedical;
     private Article article;
     private Membre membre;
     private String commentairecontent;
     private Date date2;

    public Commentaire() {
    }

    public Commentaire(AgentMedical agentMedical, Article article, Membre membre, String commentairecontent, Date date2) {
       this.agentMedical = agentMedical;
       this.article = article;
       this.membre = membre;
       this.commentairecontent = commentairecontent;
       this.date2 = date2;
    }
   
    public Integer getIdcommentaire() {
        return this.idcommentaire;
    }
    
    public void setIdcommentaire(Integer idcommentaire) {
        this.idcommentaire = idcommentaire;
    }
    public AgentMedical getAgentMedical() {
        return this.agentMedical;
    }
    
    public void setAgentMedical(AgentMedical agentMedical) {
        this.agentMedical = agentMedical;
    }
    public Article getArticle() {
        return this.article;
    }
    
    public void setArticle(Article article) {
        this.article = article;
    }
    public Membre getMembre() {
        return this.membre;
    }
    
    public void setMembre(Membre membre) {
        this.membre = membre;
    }
    public String getCommentairecontent() {
        return this.commentairecontent;
    }
    
    public void setCommentairecontent(String commentairecontent) {
        this.commentairecontent = commentairecontent;
    }
    public Date getDate2() {
        return this.date2;
    }
    
    public void setDate2(Date date2) {
        this.date2 = date2;
    }




}


