package model;
// Generated 29 mars 2016 13:18:27 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Forum generated by hbm2java
 */
public class Forum  implements java.io.Serializable {


     private Integer idforum;
     private String forumnom;
     private Set<Article> articles = new HashSet<Article>(0);
     private Set<Note> notes = new HashSet<Note>(0);

    public Forum() {
    }

    public Forum(String forumnom, Set<Article> articles, Set<Note> notes) {
       this.forumnom = forumnom;
       this.articles = articles;
       this.notes = notes;
    }
   
    public Integer getIdforum() {
        return this.idforum;
    }
    
    public void setIdforum(Integer idforum) {
        this.idforum = idforum;
    }
    public String getForumnom() {
        return this.forumnom;
    }
    
    public void setForumnom(String forumnom) {
        this.forumnom = forumnom;
    }
    public Set<Article> getArticles() {
        return this.articles;
    }
    
    public void setArticles(Set<Article> articles) {
        this.articles = articles;
    }
    public Set<Note> getNotes() {
        return this.notes;
    }
    
    public void setNotes(Set<Note> notes) {
        this.notes = notes;
    }




}


