package model;
// Generated 30 mars 2016 10:59:16 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Forum generated by hbm2java
 */
@Entity
@Table(name="forum"
    ,catalog="pcd"
)
public class Forum  implements java.io.Serializable {


     private Integer idforum;
     private String forumnom;
     private Set<Article> articles = new HashSet<Article>(0);
     private Set<Note> notes = new HashSet<Note>(0);

    public Forum() {
    }

    public Forum(String forumnom, Set<Article> articles, Set<Note> notes) {
       this.forumnom = forumnom;
       this.articles = articles;
       this.notes = notes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idforum", unique=true, nullable=false)
    public Integer getIdforum() {
        return this.idforum;
    }
    
    public void setIdforum(Integer idforum) {
        this.idforum = idforum;
    }

    
    @Column(name="forumnom")
    public String getForumnom() {
        return this.forumnom;
    }
    
    public void setForumnom(String forumnom) {
        this.forumnom = forumnom;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="forum")
    public Set<Article> getArticles() {
        return this.articles;
    }
    
    public void setArticles(Set<Article> articles) {
        this.articles = articles;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="forum")
    public Set<Note> getNotes() {
        return this.notes;
    }
    
    public void setNotes(Set<Note> notes) {
        this.notes = notes;
    }




}


