package model;
// Generated 30 mars 2016 10:59:16 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MembreDonnerNote generated by hbm2java
 */
@Entity
@Table(name="membre_donner_note"
    ,catalog="pcd"
)
public class MembreDonnerNote  implements java.io.Serializable {


     private MembreDonnerNoteId id;
     private Membre membre;
     private Note note;
     private Date date1;

    public MembreDonnerNote() {
    }

	
    public MembreDonnerNote(MembreDonnerNoteId id, Membre membre, Note note) {
        this.id = id;
        this.membre = membre;
        this.note = note;
    }
    public MembreDonnerNote(MembreDonnerNoteId id, Membre membre, Note note, Date date1) {
       this.id = id;
       this.membre = membre;
       this.note = note;
       this.date1 = date1;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idmembre", column=@Column(name="idmembre", nullable=false) ), 
        @AttributeOverride(name="idnote", column=@Column(name="idnote", nullable=false) ) } )
    public MembreDonnerNoteId getId() {
        return this.id;
    }
    
    public void setId(MembreDonnerNoteId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idmembre", nullable=false, insertable=false, updatable=false)
    public Membre getMembre() {
        return this.membre;
    }
    
    public void setMembre(Membre membre) {
        this.membre = membre;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idnote", nullable=false, insertable=false, updatable=false)
    public Note getNote() {
        return this.note;
    }
    
    public void setNote(Note note) {
        this.note = note;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date1", length=10)
    public Date getDate1() {
        return this.date1;
    }
    
    public void setDate1(Date date1) {
        this.date1 = date1;
    }




}


