package model;
// Generated 24 avr. 2016 23:55:02 by Hibernate Tools 4.3.1



/**
 * MembreDonnerNoteId generated by hbm2java
 */
public class MembreDonnerNoteId  implements java.io.Serializable {


     private int idmembre;
     private int idnote;

    public MembreDonnerNoteId() {
    }

    public MembreDonnerNoteId(int idmembre, int idnote) {
       this.idmembre = idmembre;
       this.idnote = idnote;
    }
   
    public int getIdmembre() {
        return this.idmembre;
    }
    
    public void setIdmembre(int idmembre) {
        this.idmembre = idmembre;
    }
    public int getIdnote() {
        return this.idnote;
    }
    
    public void setIdnote(int idnote) {
        this.idnote = idnote;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MembreDonnerNoteId) ) return false;
		 MembreDonnerNoteId castOther = ( MembreDonnerNoteId ) other; 
         
		 return (this.getIdmembre()==castOther.getIdmembre())
 && (this.getIdnote()==castOther.getIdnote());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdmembre();
         result = 37 * result + this.getIdnote();
         return result;
   }   


}


