package model;
// Generated 24 avr. 2016 23:55:02 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Note generated by hbm2java
 */
public class Note  implements java.io.Serializable {


     private Integer idnote;
     private Forum forum;
     private Integer notevaleur;
     private Set membreDonnerNotes = new HashSet(0);

    public Note() {
    }

    public Note(Forum forum, Integer notevaleur, Set membreDonnerNotes) {
       this.forum = forum;
       this.notevaleur = notevaleur;
       this.membreDonnerNotes = membreDonnerNotes;
    }
   
    public Integer getIdnote() {
        return this.idnote;
    }
    
    public void setIdnote(Integer idnote) {
        this.idnote = idnote;
    }
    public Forum getForum() {
        return this.forum;
    }
    
    public void setForum(Forum forum) {
        this.forum = forum;
    }
    public Integer getNotevaleur() {
        return this.notevaleur;
    }
    
    public void setNotevaleur(Integer notevaleur) {
        this.notevaleur = notevaleur;
    }
    public Set getMembreDonnerNotes() {
        return this.membreDonnerNotes;
    }
    
    public void setMembreDonnerNotes(Set membreDonnerNotes) {
        this.membreDonnerNotes = membreDonnerNotes;
    }




}


