package model;
// Generated 30 mars 2016 10:59:16 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Note generated by hbm2java
 */
@Entity
@Table(name="note"
    ,catalog="pcd"
)
public class Note  implements java.io.Serializable {


     private Integer idnote;
     private Forum forum;
     private Integer notevaleur;
     private Set<MembreDonnerNote> membreDonnerNotes = new HashSet<MembreDonnerNote>(0);

    public Note() {
    }

    public Note(Forum forum, Integer notevaleur, Set<MembreDonnerNote> membreDonnerNotes) {
       this.forum = forum;
       this.notevaleur = notevaleur;
       this.membreDonnerNotes = membreDonnerNotes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idnote", unique=true, nullable=false)
    public Integer getIdnote() {
        return this.idnote;
    }
    
    public void setIdnote(Integer idnote) {
        this.idnote = idnote;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idforum")
    public Forum getForum() {
        return this.forum;
    }
    
    public void setForum(Forum forum) {
        this.forum = forum;
    }

    
    @Column(name="notevaleur")
    public Integer getNotevaleur() {
        return this.notevaleur;
    }
    
    public void setNotevaleur(Integer notevaleur) {
        this.notevaleur = notevaleur;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="note")
    public Set<MembreDonnerNote> getMembreDonnerNotes() {
        return this.membreDonnerNotes;
    }
    
    public void setMembreDonnerNotes(Set<MembreDonnerNote> membreDonnerNotes) {
        this.membreDonnerNotes = membreDonnerNotes;
    }




}


