package model;
// Generated 27 mars 2016 14:38:31 by Hibernate Tools 4.3.1



/**
 * Offre generated by hbm2java
 */
public class Offre  implements java.io.Serializable {


     private Integer idoffre;
     private Profil profil;
     private String offrenom;

    public Offre() {
    }

    public Offre(Profil profil, String offrenom) {
       this.profil = profil;
       this.offrenom = offrenom;
    }
   
    public Integer getIdoffre() {
        return this.idoffre;
    }
    
    public void setIdoffre(Integer idoffre) {
        this.idoffre = idoffre;
    }
    public Profil getProfil() {
        return this.profil;
    }
    
    public void setProfil(Profil profil) {
        this.profil = profil;
    }
    public String getOffrenom() {
        return this.offrenom;
    }
    
    public void setOffrenom(String offrenom) {
        this.offrenom = offrenom;
    }




}


