package model;
// Generated 26 mars 2016 16:46:25 by Hibernate Tools 4.3.1



/**
 * Offre generated by hbm2java
 */
public class Offre  implements java.io.Serializable {


     private int idoffre;
     private Profil profil;
     private String offrenom;

    public Offre() {
    }

	
    public Offre(int idoffre) {
        this.idoffre = idoffre;
    }
    public Offre(int idoffre, Profil profil, String offrenom) {
       this.idoffre = idoffre;
       this.profil = profil;
       this.offrenom = offrenom;
    }
   
    public int getIdoffre() {
        return this.idoffre;
    }
    
    public void setIdoffre(int idoffre) {
        this.idoffre = idoffre;
    }
    public Profil getProfil() {
        return this.profil;
    }
    
    public void setProfil(Profil profil) {
        this.profil = profil;
    }
    public String getOffrenom() {
        return this.offrenom;
    }
    
    public void setOffrenom(String offrenom) {
        this.offrenom = offrenom;
    }




}


