package model;
// Generated 27 mars 2016 14:38:31 by Hibernate Tools 4.3.1



/**
 * Photo generated by hbm2java
 */
public class Photo  implements java.io.Serializable {


     private Integer idphoto;
     private Profil profil;
     private String phototitre;
     private String photochemin;

    public Photo() {
    }

    public Photo(Profil profil, String phototitre, String photochemin) {
       this.profil = profil;
       this.phototitre = phototitre;
       this.photochemin = photochemin;
    }
   
    public Integer getIdphoto() {
        return this.idphoto;
    }
    
    public void setIdphoto(Integer idphoto) {
        this.idphoto = idphoto;
    }
    public Profil getProfil() {
        return this.profil;
    }
    
    public void setProfil(Profil profil) {
        this.profil = profil;
    }
    public String getPhototitre() {
        return this.phototitre;
    }
    
    public void setPhototitre(String phototitre) {
        this.phototitre = phototitre;
    }
    public String getPhotochemin() {
        return this.photochemin;
    }
    
    public void setPhotochemin(String photochemin) {
        this.photochemin = photochemin;
    }




}


