package model;
// Generated 30 mars 2016 10:59:16 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Photo generated by hbm2java
 */
@Entity
@Table(name="photo"
    ,catalog="pcd"
)
public class Photo  implements java.io.Serializable {


     private Integer idphoto;
     private Profil profil;
     private String phototitre;
     private String photochemin;

    public Photo() {
    }

    public Photo(Profil profil, String phototitre, String photochemin) {
       this.profil = profil;
       this.phototitre = phototitre;
       this.photochemin = photochemin;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idphoto", unique=true, nullable=false)
    public Integer getIdphoto() {
        return this.idphoto;
    }
    
    public void setIdphoto(Integer idphoto) {
        this.idphoto = idphoto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idprofil")
    public Profil getProfil() {
        return this.profil;
    }
    
    public void setProfil(Profil profil) {
        this.profil = profil;
    }

    
    @Column(name="phototitre")
    public String getPhototitre() {
        return this.phototitre;
    }
    
    public void setPhototitre(String phototitre) {
        this.phototitre = phototitre;
    }

    
    @Column(name="photochemin")
    public String getPhotochemin() {
        return this.photochemin;
    }
    
    public void setPhotochemin(String photochemin) {
        this.photochemin = photochemin;
    }




}


