package model;
// Generated 26 mars 2016 16:46:25 by Hibernate Tools 4.3.1



/**
 * Photo generated by hbm2java
 */
public class Photo  implements java.io.Serializable {


     private int idphoto;
     private Profil profil;
     private String phototitre;
     private String photochemin;

    public Photo() {
    }

	
    public Photo(int idphoto) {
        this.idphoto = idphoto;
    }
    public Photo(int idphoto, Profil profil, String phototitre, String photochemin) {
       this.idphoto = idphoto;
       this.profil = profil;
       this.phototitre = phototitre;
       this.photochemin = photochemin;
    }
   
    public int getIdphoto() {
        return this.idphoto;
    }
    
    public void setIdphoto(int idphoto) {
        this.idphoto = idphoto;
    }
    public Profil getProfil() {
        return this.profil;
    }
    
    public void setProfil(Profil profil) {
        this.profil = profil;
    }
    public String getPhototitre() {
        return this.phototitre;
    }
    
    public void setPhototitre(String phototitre) {
        this.phototitre = phototitre;
    }
    public String getPhotochemin() {
        return this.photochemin;
    }
    
    public void setPhotochemin(String photochemin) {
        this.photochemin = photochemin;
    }




}


