package model;
// Generated 5 avr. 2016 13:48:20 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Profil generated by hbm2java
 */
public class Profil  implements java.io.Serializable {


     private Integer idprofil;
     private AgentMedical agentMedical;
     private String profilnom;
     private Set photos = new HashSet(0);
     private Set offres = new HashSet(0);

    public Profil() {
    }

    public Profil(AgentMedical agentMedical, String profilnom, Set photos, Set offres) {
       this.agentMedical = agentMedical;
       this.profilnom = profilnom;
       this.photos = photos;
       this.offres = offres;
    }
   
    public Integer getIdprofil() {
        return this.idprofil;
    }
    
    public void setIdprofil(Integer idprofil) {
        this.idprofil = idprofil;
    }
    public AgentMedical getAgentMedical() {
        return this.agentMedical;
    }
    
    public void setAgentMedical(AgentMedical agentMedical) {
        this.agentMedical = agentMedical;
    }
    public String getProfilnom() {
        return this.profilnom;
    }
    
    public void setProfilnom(String profilnom) {
        this.profilnom = profilnom;
    }
    public Set getPhotos() {
        return this.photos;
    }
    
    public void setPhotos(Set photos) {
        this.photos = photos;
    }
    public Set getOffres() {
        return this.offres;
    }
    
    public void setOffres(Set offres) {
        this.offres = offres;
    }




}


