package model;
// Generated 30 mars 2016 10:59:16 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Profil generated by hbm2java
 */
@Entity
@Table(name="profil"
    ,catalog="pcd"
)
public class Profil  implements java.io.Serializable {


     private Integer idprofil;
     private AgentMedical agentMedical;
     private String profilnom;
     private Set<Photo> photos = new HashSet<Photo>(0);
     private Set<Offre> offres = new HashSet<Offre>(0);

    public Profil() {
    }

    public Profil(AgentMedical agentMedical, String profilnom, Set<Photo> photos, Set<Offre> offres) {
       this.agentMedical = agentMedical;
       this.profilnom = profilnom;
       this.photos = photos;
       this.offres = offres;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idprofil", unique=true, nullable=false)
    public Integer getIdprofil() {
        return this.idprofil;
    }
    
    public void setIdprofil(Integer idprofil) {
        this.idprofil = idprofil;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idagent")
    public AgentMedical getAgentMedical() {
        return this.agentMedical;
    }
    
    public void setAgentMedical(AgentMedical agentMedical) {
        this.agentMedical = agentMedical;
    }

    
    @Column(name="profilnom")
    public String getProfilnom() {
        return this.profilnom;
    }
    
    public void setProfilnom(String profilnom) {
        this.profilnom = profilnom;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="profil")
    public Set<Photo> getPhotos() {
        return this.photos;
    }
    
    public void setPhotos(Set<Photo> photos) {
        this.photos = photos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="profil")
    public Set<Offre> getOffres() {
        return this.offres;
    }
    
    public void setOffres(Set<Offre> offres) {
        this.offres = offres;
    }




}


