package model;
// Generated 24 avr. 2016 23:55:02 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Statistique generated by hbm2java
 */
public class Statistique  implements java.io.Serializable {


     private Integer idstat;
     private Set administrateurs = new HashSet(0);

    public Statistique() {
    }

    public Statistique(Set administrateurs) {
       this.administrateurs = administrateurs;
    }
   
    public Integer getIdstat() {
        return this.idstat;
    }
    
    public void setIdstat(Integer idstat) {
        this.idstat = idstat;
    }
    public Set getAdministrateurs() {
        return this.administrateurs;
    }
    
    public void setAdministrateurs(Set administrateurs) {
        this.administrateurs = administrateurs;
    }




}


