package model;
// Generated 30 mars 2016 10:59:16 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Visiteur generated by hbm2java
 */
@Entity
@Table(name="visiteur"
    ,catalog="pcd"
)
public class Visiteur  implements java.io.Serializable {


     private Integer numvisiteur;

    public Visiteur() {
    }

   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="numvisiteur", unique=true, nullable=false)
    public Integer getNumvisiteur() {
        return this.numvisiteur;
    }
    
    public void setNumvisiteur(Integer numvisiteur) {
        this.numvisiteur = numvisiteur;
    }




}


