package model;
// Generated 26 mars 2016 16:46:25 by Hibernate Tools 4.3.1



/**
 * Visiteur generated by hbm2java
 */
public class Visiteur  implements java.io.Serializable {


     private int numvisiteur;

    public Visiteur() {
    }

    public Visiteur(int numvisiteur) {
       this.numvisiteur = numvisiteur;
    }
   
    public int getNumvisiteur() {
        return this.numvisiteur;
    }
    
    public void setNumvisiteur(int numvisiteur) {
        this.numvisiteur = numvisiteur;
    }




}


